groups:
  - name: web_unhealth
    rules:
      - alert: web_unhealth
        expr: up{job="web"} == 0
        for: 10s
        labels:
          role: web
          type: stability
        annotations:
          summary: "web is out of service"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has out of service for more than 10 sec."
          username: "@channel"
  - name: web_gets_many_requests
    rules:
      - alert: web_gets_many_requests
        expr: rate(request_in_total{job="web"}[10s]) > 10
        for: 10s
        labels:
          role: web
          type: stability
        annotations:
          summary: ""
          description: "{{ $labels.instance }} of job {{ $labels.job }} has over 60 requests/minute for more than 10 sec."
          username: "@channel"
