name: deploy to dev manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: target version (SHA or TAG)
        default: v1.0.0
        required: true

jobs:
  info:
    name: info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show basic information
        run: |
          echo GITHUB_WORKFLOW: ${{ github.workflow }}
          echo GITHUB_EVENT_NAME: ${{ github.event.name }}
          echo deploy version ${{ github.event.inputs.version }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |

            ###
            ### init variables
            ###
            VERSION=${GITHUB_SHA:0:8}
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
            IMAGE_ID_VERSION=${IMAGE_ID}:${VERSION}
            echo IMAGE_ID_VERSION: ${IMAGE_ID_VERSION}

            ###
            ### deploy service with docker-compose file
            ###
            echo --> pull latest docker-compose from github
            echo --> pull target image based on IMAGE_ID_VERSION
            echo --> set up service by docker-compose
